version: '3'
services:
  sensor-api:
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://iotconsumer_mysql-standalone_1:3306/test?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
networks:
  default:
    external: true
    name: iotconsumer_mysql-network