version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network
  kafka_0:
    image: wurstmeister/kafka:latest
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_0:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      KAFKA_CREATE_TOPICS: "iot-data:3:3"
    networks:
      - kafka-network
  kafka_1:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_1:29093,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENERS: PLAINTEXT://:29093,PLAINTEXT_HOST://:9094
      KAFKA_CREATE_TOPICS: "iot-data:3:3"
    networks:
      - kafka-network
  kafka_2:
    image: wurstmeister/kafka:latest
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9095:9095"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_2:29094,PLAINTEXT_HOST://localhost:9095
      KAFKA_LISTENERS: PLAINTEXT://:29094,PLAINTEXT_HOST://:9095
      KAFKA_CREATE_TOPICS: "iot-data:3:3"
    networks:
      - kafka-network
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka_0:29092,kafka_1:29093, kafka_2:29094"
    depends_on:
      - "kafka_0"
      - "kafka_1"
      - "kafka_2"
    networks:
      - kafka-network
  producer-api:
    build:
        dockerfile: docker/dev.Dockerfile
        context: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - app-network
      - kafka-network
    depends_on:
      - kafka_0

networks:
  kafka-network:
  app-network: