server:
  port: 7000

spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
          - kafka_0:29092
      bindings:
        input:
         binder: kafka
         destination: iot-data
         content-type: application/json
         group: input-group-1
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password:

  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update